services:

  ingestion:
    build: ./ingestion
    env_file: .env
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw

  transform:
    build: ./transform
    env_file: .env
    depends_on:
      - kafka
      - timescaledb

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hitlab
      POSTGRES_PASSWORD: hitlab
      POSTGRES_DB: hitlab
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  dashboard:
    build: ./dashboard
    env_file: .env
    ports:
      - "8501:8501"
    depends_on:
      - timescaledb

volumes:
  timescaledb_data:
